const Discord = require('discord.js');
const errors = require("../../controllers/error");

module.exports = {
	name: 'check',
	description: 'Checks if a target is valid for the shiny trainer challenge.',
    args: true,
    usage: '<pokemon-name>',
	async execute(message, args) {
        const target = message.author;
		const pokemon = args[0].toLowerCase();
        console.log("pokemon: ", pokemon)

		try{

            let pokemonList = [
                "bulbasaur", "ivysaur", "venusaur",
                "charmander", "charmeleon", "charizard",
                "squirtle", "wartortle", "blastoise",
                "weedle", "kakuna", "beedrill",
                "pidgey","pidgeotto","pidgeot",
                "spearow", "fearow",
                "pikachu", "raichu",
                "nidoran", "nidoranm", "nidoranmale", "nidoran♂", "nidorino", "nidoking",
                "clefairy", "clefable",
                "vulpix", "ninetales",
                "zubat", "golbat",
                "growlithe", "arcanine",
                "poliwag","poliwhirl",
                "abra","kadabra","alakazam",
                "geodude", "graveler", "golem",
                "ponyta", "rapidash",
                "slowpoke", "slowbro",
                "magnemite", "magneton",
                "farfetch'd", "farfetchd",
                "gastly","haunter","gengar",
                "onix",
                "krabby", "kingler",
                "hitmonlee",
                "hitmonchan",
                "rhyhorn", "rhydon",
                "mr", "mr.", "mr.mime", "mrmime",
                "scyther",
                "jynx",
                "electabuzz",
                "magmar",
                "magikarp", "gyarados",
                "ditto",
                "eevee", "vaporeon", "jolteon", "flareon",
                "porygon",
                "aerodactyl",
                "snorlax",
                "articuno","zapdos","moltres",
                "dratini", "dragonair", "dragonite",
                "mewtwo",
                "chikorita", "bayleef", "meganium",
                "cyndaquil", "quilava", "typhlosion",
                "totodile", "croconaw", "feraligatr",
                "sentret", "furret",
                "spinarak", "ariados",
                "crobat",
                "chinchou", "lanturn",
                "pichu",
                "cleffa",
                "togepi", "togetic",
                "mareep", "flaaffy", "ampharos",
                "marill", "azumarill",
                "sudowoodo",
                "politoed",
                "hoppip", "skiploom", "jumpluff",
                "aipom",
                "sunkern", "sunflora",
                "yanma",
                "wooper", "quagsire",
                "espeon",
                "umbreon",
                "murkrow",
                "unown",
                "girafarig",
                "gligar",
                "steelix",
                "snubbull", "granbull",
                "scizor",
                "heracross",
                "sneasel",
                "slugma", "magcargo",
                "swinub", "piloswine",
                "remoraid", "octillery",
                "delibird",
                "skarmory",
                "houndour", "houndoom",
                "kingdra",
                "porygon2",
                "tyrogue", "hitmontop",
                "smoochum",
                "elekid",
                "magby",
                "raikou","entei","suicune",
                "larvitar", "pupitar", "tyranitar",
                "celebi",
                "treecko", "grovyle", "sceptile",
                "torchic", "combusken", "blaziken",
                "mudkip", "marshtomp", "swampert",
                "poochyena", "mightyena",
                "zigzagoon", "linoone",
                "wurmple", "silcoon", "beautifly", "cascoon", "dustox",
                "lotad", "lombre", "ludicolo",
                "taillow", "swellow",
                "wingull", "pelipper",
                "ralts", "kirlia", "gardevoir",
                "surskit", "masquerain",
                "shroomish", "breloom",
                "nincada","ninjask","shedninja",
                "azurill",
                "nosepass",
                "mawile",
                "aron", "lairon", "aggron",
                "meditite", "medicham",
                "electrike", "manectric",
                "plusle",
                "roselia",
                "carvanha", "sharpedo",
                "wailmer", "wailord",
                "numel", "camerupt",
                "torkoal",
                "trapinch", "vibrava", "flygon",
                "swablu", "altaria",
                "zangoose",
                "seviper",
                "lunatone",
                "solrock",
                "barboach", "whiscash",
                "anorith", "armaldo",
                "feebas", "milotic",
                "duskull", "dusclops",
                "absol",
                "snorunt",
                "spheal", "sealeo", "walrein",
                "clamperl", "huntail",
                "relicanth",
                "bagon", "shelgon", "salamence",
                "beldum", "metang", "metagross",
                "rayquaza",
                "deoxys",
                "turtwig", "grotle", "torterra",
                "chimchar", "monferno", "infernape",
                "piplup", "prinplup", "empoleon",
                "starly", "staravia", "staraptor",
                "shinx", "luxio", "luxray",
                "budew", "roserade",
                "cranidos", "rampardos",
                "shieldon", "bastiodon",
                "combee", "vespiquen",
                "pachirisu",
                "buizel", "floatzel",
                "cherubi", "cherrim",
                "shellos", "gastrodon",
                "ambipom",
                "drifloon", "drifblim",
                "buneary", "lopunny",
                "honchkrow",
                "bronzor", "bronzong",
                "bonsly",
                "mime","mimejr.", "mimejr",
                "spiritomb",
                "gible", "gabite", "garchomp",
                "munchlax",
                "riolu", "lucario",
                "hippopotas", "hippowdon",
                "skorupi", "drapion",
                "croagunk", "toxicroak",
                "snover", "abomasnow",
                "weavile",
                "magnezone",
                "rhyperior",
                "electivire",
                "magmortar",
                "togekiss",
                "yanmega",
                "leafeon",
                "glaceon",
                "gliscor",
                "mamoswine",
                "porygon-z",
                "gallade",
                "probopass",
                "dusknoir",
                "froslass",
                "rotom",
                "palkia",
                "giratina",
                "darkrai",
                "shaymin",
                "arceus",
                "snivy", "servine", "serperior",
                "tepig", "pignite", "emboar",
                "oshawott", "dewott", "samurott",
                "purrloin", "liepard",
                "pansage", "simisage",
                "pansear", "simisear",
                "panpour", "semipour",
                "munna", "musharna",
                "pidove", "tranquill", "unfezant",
                "roggenrola", "boldore", "gigalith",
                "drilbur", "excadrill",
                "audino",
                "venipede", "whirlipede", "scolipede",
                "cottonee", "whimsicott",
                "petilil", "lilligant",
                "sandile", "krokorok", "krookodile",
                "darumaka", "darmanitan",
                "scraggy", "scrafty",
                "sigilyph",
                "yamask", "cofagrigus",
                "tirtouga", "carracosta",
                "archen", "archeops",
                "zorua", "zoroark",
                "minccino", "cinccino",
                "ducklett", "swanna",
                "deerling", "sawsbuck",
                "karrablast", "escavalier",
                "axew", "fraxure", "haxorus",
                "mienfoo", "mienshao",
                "golett", "golurk",
                "pawniard", "bisharp",
                "larvesta", "volcarona",
                "zekrom",
                "keldeo",
                "meloetta",
                "genesect",
                "chespin", "quilladin", "chesnaught",
                "fennekin", "braixen", "delphox",
                "froakie", "frogadier", "greninja",
                "bunnelby", "diggersby",
                "vivillon",
                "flabébé", "flabebe", "floette", "florges",
                "skiddo", "gogoat",
                "espurr", "meowstic",
                "honedge", "doublade", "aegislash",
                "spritzee", "aromatisse",
                "swirlix", "slurpuff",
                "tyrunt", "tyrantrum",
                "amaura", "aurorus",
                "sylveon",
                "goomy", "sliggoo", "goodra",
                "noibat", "noivern",
                "xerneas",
                "yveltal",
                "zygarde",
                "diancie",
                "hoopa",
                "volcanion",
                "rowlet", "dartrix", "decidueye",
                "popplio", "brionne", "primarina",
                "pikipek", "trumbeak", "toucannon",
                "grubbin", "charjabug", "vikavolt",
                "rockruff", "lycanroc",
                "dewpider", "araquanid",
                "salandit", "salazzle",
                "oranguru",
                "wimpod", "golisopod",
                "sandygast", "palossand",
                "type", "type:null", "silvally",
                "mimikyu",
                "dhelmise",
                "tapu", "tapukoko", "tapulele", "tapubulu", "tapufini",
                "cosmog", "cosmoem", "solgaleo", "lunala",
                "nihilego",
                "buzzwole",
                "pheromosa",
                "xurkitree",
                "celesteela",
                "kartana",
                "guzzlord",
                "necrozma",
                "magearna",
                "marshadow",
                "poipole", "naganadel",
                "stakataka",
                "blacephalon",
                "zeraora",
                "meltan", "melmetal",
                "scorbunny", "raboot", "cinderace",
                "rookidee", "corvisquire", "corviknight",
                "toxel", "toxtricity",
                "sizzlipede", "centiskorch",
                "hatenna", "hattrem", "hatterene",
                "impidimp", "morgrem", "grimmsnarl",
                "obstagoon",
                "perrserker",
                "sirfetch'd",
                "rime", "mr.rime", "mrrime",
                "runerigus",
                "pincurchin",
                "indeedee",
                "morpeko",
                "cufant", "copperajah",
                "dreepy", "drakloak", "dragapult",
                "zacian", "zamazenta",
                "eternatus",
                "kubfu", "urshifu",
                "zarude",
                "glastrier","spectrier",
                "calyrex"
            ]

            if(pokemonList.includes(pokemon)){
                return message.channel.send(`${pokemon} is a valid target, get hunting!`)
            }
            return message.channel.send(`${pokemon} isn't a valid target, it may be one day though!`)

		}catch (err){
			console.error(err.message)
			return errors.errorMessage(message)
		}
	},
};
